Add account CTA and rename functionality
trilitech/umami-v2 pull request #1618
Opened 2024-07-24 11:27 UTC by OKendigelyan

## Proposed changes

[Task link](https://app.asana.com/0/1207041888417083/1207811126378442/f)

## Types of changes

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor
- [ ] Breaking change
- [ ] UI fix

## Steps to reproduce

## Screenshots

Add the screenshots of how the app used to look like and how it looks now

| Before | Now |
| ------ | --- |
|        |     |

## Checklist

- [ ] Tests that prove my fix is effective or that my feature works have been added
- [ ] Documentation has been added (if appropriate)
- [ ] Screenshots are added (if any UI changes have been made)
- [ ] All TODOs have a corresponding task created (and the link is attached to it)

2024-07-26 17:07 UTC, asiia-trilitech commented on apps/web/src/components/AccountSelectorModal/RemoveAccountModal.tsx
> +  let description =
I think Figma has slightly different description & button text: https://www.figma.com/design/kUJJ7T75lP4GPNMg4GMVt1/Embed-%26-Web?node-id=595-22299&t=tk0S3nUQLcCw7EUN-0

2024-07-26 17:33 UTC, asiia-trilitech commented on apps/web/src/components/AccountSelectorModal/AccountInfoModal.tsx
> +    goBack();
Should the modal get closed on copying the address? 
On desktop in similar cases we show toast and keep the modal open

2024-07-26 17:41 UTC, asiia-trilitech commented on apps/web/src/components/AccountSelectorModal/AccountSelectorPopover.tsx
> +      window.open(`https://tzkt.io/${account.address.pkh}`, "_blank");
It's opening mainnet atm - can we open tzkt with the selected network?

2024-07-29 13:40 UTC, serjonya-trili requested changes
1. Copy address button should show a "Copied" popover instead of coming back
2. When a sub-modal is closed, it should return user back to the previous modal (e.g. open account selector)
3. Open on Tzkt should work for ghostnet too. right now it always opens the mainnet

2024-07-29 13:40 UTC, serjonya-trili commented on apps/web/src/components/AccountSelectorModal/AccountInfoModal.tsx
> +          <Text maxWidth="340px" color="gray.700" fontWeight="400" size="md">
please use the useColor where possible

2024-07-29 13:40 UTC, serjonya-trili commented on apps/web/src/components/AccountSelectorModal/AccountInfoModal.tsx
> +            borderWidth={1.5}
please use the actual units

2024-07-29 13:40 UTC, serjonya-trili commented on apps/web/src/components/AccountSelectorModal/AccountSelectorPopover.tsx
> +                  <Flex
this should be a button. maybe with a separate variant

2024-07-29 13:40 UTC, serjonya-trili commented on apps/web/src/components/AccountSelectorModal/AccountSelectorPopover.tsx
> +const accountSelectorPopoverOptions = [
I think it'd be much cleaner if you just inlined it

2024-07-29 13:40 UTC, serjonya-trili commented on apps/web/src/components/Menu/Menu.tsx
> +    navigate("/");
with this, it's likely that the persistor will still be paused which is not exactly what we expect

2024-07-30 11:25 UTC, OKendigelyan commented
> 2. When a sub-modal is closed, it should return user back to the previous modal (e.g. open account selector)
will be implemented in this ticket https://app.asana.com/0/1207041888417083/1207893626622358/f

2024-07-30 12:33 UTC, serjonya-trili commented on apps/web/src/components/AccountSelectorModal/AccountInfoModal.tsx
> +  const handleCopyAddress = async () => {
maybe shorten to:

```typescript
const handleCopyAddress = () => navigator.clipboard.writeText(account.address.pkh);
```
?

2024-07-30 12:37 UTC, serjonya-trili commented on apps/web/src/styles/theme.ts
> +          w: "full",
please avoid using these shorthands. it's too easy to make a mistake with those.

2024-07-30 12:55 UTC, OKendigelyan commented on apps/web/src/assets/icons/index.ts
> +import CloseIcon from "./close.svg";
`close.svg` is relevant icon from the figma

2024-07-30 15:31 UTC, serjonya-trili requested changes

2024-07-30 15:31 UTC, serjonya-trili commented on apps/web/src/components/AccountSelectorModal/AccountInfoModal.test.tsx
> +    await act(async () => {
```typescript
await act(() => user.click(screen.getByRole("button", { name: /copy wallet address/i })));
```
is shorter

2024-07-30 15:31 UTC, serjonya-trili commented on apps/web/src/components/AccountSelectorModal/AccountInfoModal.test.tsx
> +const mockAccount = {
we have helpers for this. like mockImplicitAccount

2024-07-30 15:31 UTC, serjonya-trili commented on apps/web/src/components/AccountSelectorModal/AccountInfoModal.test.tsx
> +    expect(screen.getByText("Account Info")).toBeInTheDocument();
it's better to use `toBeVisible()`, and in other places too

2024-07-30 15:31 UTC, serjonya-trili commented on apps/web/src/components/AccountSelectorModal/AccountSelectorPopover.test.tsx
> +    (useDynamicDisclosureContext as jest.Mock).mockReturnValue({
it's already available to you with the `dynamicDisclosureContextMock`. please check testUtils.tsx

2024-07-30 15:31 UTC, serjonya-trili commented on apps/web/src/components/AccountSelectorModal/AccountSelectorPopover.test.tsx
> +    (useSelectedNetwork as jest.Mock).mockReturnValue(mockNetwork);
it's better to use mainnet VS ghostnet instead

2024-07-30 15:31 UTC, serjonya-trili commented on apps/web/src/components/AccountSelectorModal/AccountSelectorPopover.test.tsx
> +    const { openWith } = useDynamicDisclosureContext();
please use `dynamicDisclosureContextMock` instead

2024-07-30 15:31 UTC, serjonya-trili commented on apps/web/src/components/AccountSelectorModal/AccountSelectorPopover.tsx
> +                onClick={async e => {
nit: there is no need for async await.

you can just `return openWith(...)`
(and in other places too)

2024-07-30 15:31 UTC, serjonya-trili commented on apps/web/src/components/AccountSelectorModal/RenameAccountModal.tsx
> +            <EditIcon width="22px" color={light.blue} />
why not `color={color("blue")}` ?

2024-07-31 12:46 UTC, serjonya-trili requested changes

2024-07-31 12:46 UTC, serjonya-trili commented on apps/web/src/components/AccountSelectorModal/AccountSelectorPopover.tsx
> +                  window.open(url, "_blank");
this is a security issue https://docs.datadoghq.com/code_analysis/static_analysis_rules/jsx-react/jsx-no-target-blank/

please use a `<Link isExternal` instead. [Example](https://github.com/trilitech/umami-v2/pull/1650/files#diff-ada356f9b19ff984f99256292da9132e180abdb48ab4db214f6b084d9429b155R49)

2024-07-31 12:46 UTC, serjonya-trili commented on apps/web/src/components/AccountSelectorModal/RemoveAccountModal.test.tsx
> +    render(<RemoveAccountModal account={{} as any} />);
and if you do prepare the state, you wouldn't need to pass this meaningless value here

2024-07-31 15:18 UTC, serjonya-trili commented on apps/web/src/components/AccountSelectorModal/RenameAccountModal.test.tsx
> +    await act(() => user.click(screen.getByRole("button", { name: /update/i })));
please use exact strings where possible

2024-07-31 15:19 UTC, serjonya-trili commented on apps/web/src/components/AccountSelectorModal/RemoveAccountModal.test.tsx
> +    (useRemoveAccount as jest.Mock).mockReturnValue(mockRemoveAccount);
please use `jest.mocked(useRemoveAccount)` instead

2024-07-31 15:40 UTC, serjonya-trili approved these changes

2024-08-01 09:52 UTC, merged