Allow custom embed & web domains in auth
trilitech/umami-v2 pull request #1763
Opened 2024-08-21 08:39 UTC by serjonya-trili

this allows us to have social login through custom domains (which we use for vercel previews)
<img width="801" alt="Screenshot 2024-08-21 at 09 34 19" src="https://github.com/user-attachments/assets/5b7176b3-c81a-48f1-8b9f-75a93a6078f3">

2024-08-21 16:04 UTC, asiia-trilitech requested changes
Shouldn't these two also be updated by removing redirect surface?

https://github.com/trilitech/umami-v2/blob/main/apps/embed-iframe/src/LoginModalContent.tsx#L41

https://github.com/trilitech/umami-v2/blob/main/apps/embed-iframe/src/SignOperationModalContent.tsx#L50

2024-08-22 05:34 UTC, serjonya-trili commented on packages/social-auth/src/Auth.ts
> +      redirectToOpener: window.location.origin as any as boolean,
it's `"file://"`, since it doesn't match the regex it'll go to the other branch which is for desktop

2024-08-22 05:35 UTC, serjonya-trili commented on apps/oauth/public/redirect.html
> +            if (instanceParams.redirectToOpener === "embed") {
If that's not deployed anywhere yet we can remove it

2024-08-22 06:00 UTC, asiia-trilitech requested changes
Please consider updating these files

https://github.com/trilitech/umami-v2/blob/main/apps/embed-iframe/src/LoginModalContent.tsx#L41

https://github.com/trilitech/umami-v2/blob/main/apps/embed-iframe/src/SignOperationModalContent.tsx#L50

Given that arguments of shared Auth.forIDP() were changed, umami-embed will likely be broken by this PR if not updated

2024-08-22 12:56 UTC, asiia-trilitech approved these changes
Thank you Sergey, nice solution - approved

2024-08-22 13:02 UTC, merged