Add account derivation for mnemonic users
trilitech/umami-v2 pull request #1853
Opened 2024-09-06 13:34 UTC by OKendigelyan

## Proposed changes

[Task link](https://app.asana.com/0/1207041888417083/1208109932369871/f)

## Types of changes

- [ ] Bugfix
- [x] New feature
- [ ] Refactor
- [ ] Breaking change
- [ ] UI fix

## Steps to reproduce

## Screenshots

Add the screenshots of how the app used to look like and how it looks now

| Before | Now |
| ------ | --- |
|        |     |

## Checklist

- [x] Tests that prove my fix is effective or that my feature works have been added
- [ ] Documentation has been added (if appropriate)
- [x] Screenshots are added (if any UI changes have been made)
- [ ] All TODOs have a corresponding task created (and the link is attached to it)

2024-09-09 16:11 UTC, asiia-trilitech requested changes
Thank you, Oleg!

No issues with deriving logic, but please take a look at the comments regarding
- `+` button
- `goToIndex` in `DynamicDisclosure`

2024-09-09 16:11 UTC, asiia-trilitech commented on apps/web/src/components/NameAccountModal/NameAccountModal.tsx
We should check that account name is valid before proceeding (similar to RenameAccountModal check)

2024-09-09 16:11 UTC, asiia-trilitech commented on apps/web/src/components/MasterPasswordModal/MasterPasswordModal.tsx
Although the warning is shown, maybe we can also make the form invalid on entering wrong password
<img width="568" alt="Screenshot 2024-09-09 at 17 02 47" src="https://github.com/user-attachments/assets/34503529-89e0-455a-bce2-9da8ebe7e03a">

2024-09-09 16:11 UTC, asiia-trilitech commented on apps/web/src/components/AccountSelectorModal/DeriveMnemonicAccountModal/DeriveMnemonicAccountModal.test.tsx
> +
Maybe we can also check the case with incorrect password

And that after successful deriving, the modal will be closed

2024-09-10 11:00 UTC, OKendigelyan commented on packages/components/.eslintrc.cjs
> +        "import/no-unused-modules": "off",
the rule fixes eslint, which does not work in the `components` package

2024-09-10 11:05 UTC, OKendigelyan commented on apps/web/src/components/AccountSelectorModal/AccountSelectorModal.tsx
> +                  <IconButton
From the business perspective this button should open `Add new account modal` for any accounts other than mnemonic

2024-09-10 11:15 UTC, OKendigelyan commented on packages/components/src/DynamicDisclosure/DynamicDisclosure.test.tsx
> +      it("goToIndex should go back one step when is called with out-of-bounds index", async () => {
Previously, this logic was implemented in the `goBack` function, but after discussing it with @serjonya-trili, we decided to split this logic and keep both functions for different purposes - goBack for going directly to the previous disclosure and goToIndex for navigating through different disclosures

2024-09-10 11:23 UTC, OKendigelyan commented on apps/web/src/components/NameAccountModal/NameAccountModal.tsx
we don't need these validation rules for this case since Account name field in this modal is optional. `
Basically logic of `NameAccountModal` is the same as for desktop's `NameAccountDisplay`

2024-09-10 11:25 UTC, OKendigelyan commented on apps/web/src/components/MasterPasswordModal/MasterPasswordModal.tsx
Password validation takes place inside `useDeriveMnemonicAccount`. We don't know if the password is valid or not until we process `useDeriveMnemonicAccount`

2024-09-11 15:56 UTC, asiia-trilitech approved these changes
Thank you @OKendigelyan 👍

2024-09-12 10:12 UTC, merged