feat: WalletConnect, prototype
trilitech/umami-v2 pull request #1933
Opened 2024-09-23 09:55 UTC by dianasavvatina

Working WalletConnect integration PROTOTYPE with Umami:
 - listing dApps connected with WalletConnect
 - tezos_getAccounts returns the current account
 - tezos_sign signs payload with the current account
 - tezos_send supports all perations:
   - transaction signing
   - delegate / undelegate
   - origination, calling smart contract
   - stake, unstake, finalize
 - approve and reject by user
 - success and error from Tezos node

Study:
 - [Notion](https://www.notion.so/tezosfoundation/WalletConnect-prototype-b7ae9f2b8df84b8498986eb27803392f)
 - Prototype [slides](https://docs.google.com/presentation/d/1lJMB9mUopHvN0a_k_raTWglsamihbSat2N039vgLPxQ/edit#slide=id.p) 

Limitations:
 - the operation result is not shown to the user
 - pairings list doesn't work on remote disconnect
 - no tests
 - no documentation
 - several lint errors

## Proposed changes

This is a prototype which is not intended to be Merged.
We are going to use it as a reference for a full implementation.

## Types of changes

- [ ] Bugfix
- [x] New feature
- [ ] Refactor
- [ ] Breaking change
- [ ] UI fix

## Steps to reproduce

- run Umami web
- run test dapp, e.g. WalletConnect example [react-dapp-v2](https://github.com/reown-com/web-examples/pull/695)

## Screenshots

Add the screenshots of how the app used to look like and how it looks now

<img width="375" alt="image" src="https://github.com/user-attachments/assets/3a4570dd-4532-43fd-bec0-6ef5eaf02438">
<img width="380" alt="image" src="https://github.com/user-attachments/assets/51b5fbd4-7fe9-46f0-a199-4fbb7a5f3533">
<img width="384" alt="image" src="https://github.com/user-attachments/assets/a20aa8a6-d68a-4e84-8525-87f2bbf13229">
<img width="380" alt="image" src="https://github.com/user-attachments/assets/640c9902-5c7b-4f5b-b4d6-aae3f699a9e6">
<img width="384" alt="image" src="https://github.com/user-attachments/assets/234e5d0f-e2bf-4edb-b5f6-afc8d08c3249">

## Checklist

- [ ] Tests that prove my fix is effective or that my feature works have been added
- [ ] Documentation has been added (if appropriate)
- [x] Screenshots are added (if any UI changes have been made)
- [ ] All TODOs have a corresponding task created (and the link is attached to it)

2024-09-30 11:04 UTC, serjonya-trili requested changes

2024-09-30 11:04 UTC, serjonya-trili commented on packages/state/src/hooks/beacon.ts
> +          description: `Beacon sync code in the clipboard is INVALID. Please copy a beacon sync code from the dApp: ${payload}`,
please don't do that. it might be huge and doesn't really help the end user

2024-09-30 11:04 UTC, serjonya-trili commented on packages/state/src/hooks/beacon.ts
> +  return async (payload: string) =>
this is not necessary as we don't use the `await`s here

2024-09-30 11:04 UTC, serjonya-trili commented on apps/web/package.json
> +    "valtio": "^2.0.0",
I am sure we don't need it. most likely you need to use redux that's already included

2024-09-30 11:04 UTC, serjonya-trili commented on apps/web/src/components/SendFlow/WalletConnect/PairingCard.tsx
> +interface IProps {
we don't use interfaces, `type` is preferred

2024-09-30 11:04 UTC, serjonya-trili commented on apps/web/src/components/SendFlow/WalletConnect/PairingCard.tsx
> +  name?: string
why all the props are optional?

2024-09-30 11:04 UTC, serjonya-trili commented on packages/state/src/hooks/SettingsStore.ts
> +export const SettingsStore = {
this whole thing seems to be either already accessible or it could replicate what's already in the `beaconSlice`

2024-09-30 11:06 UTC, serjonya-trili commented on apps/web/src/components/WalletConnect/ChainDataMini.tsx
> +  if (!chainData) {return <></>;}
return null

2024-09-30 11:07 UTC, serjonya-trili commented on apps/web/src/components/WalletConnect/ChainCard.tsx
> +interface Props {
this interface can be replaced with `PropsWithChildren<CardProps>`

2024-09-30 11:10 UTC, serjonya-trili commented on apps/web/src/components/WalletConnect/SessionSignTezosModal.tsx
> +  const onApprove = async () => {
most of its loading & error handling logic is already in asyncActionHandler

2024-12-17 10:27 UTC, closed without merging

2024-12-17 10:28 UTC, dianasavvatina commented
it was only a prototype